apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oto

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - postgres.yaml
  - oto.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: oto
  app.kubernetes.io/managed-by: kustomize
