apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shellguard-db-data
  namespace: shellguard
  labels:
    app.kubernetes.io/name: shellguard
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shellguard-user-data
  namespace: shellguard
  labels:
    app.kubernetes.io/name: shellguard
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
