apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oto-db-data
  namespace: oto
  labels:
    app.kubernetes.io/name: oto
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oto-user-data
  namespace: oto
  labels:
    app.kubernetes.io/name: oto
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
